#   _________ __                      .__    .__        
#  /   _____//  |______ _______  _____|  |__ |__|_____  
#  \_____  \\   __\__  \\_  __ \/  ___/  |  \|  \____ \ 
#  /        \|  |  / __ \|  | \/\___ \|   Y  \  |  |_> >
# /_______  /|__| (____  /__|  /____  >___|  /__|   __/ 
#         \/           \/           \/     \/   |__|    

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$character\
"""
right_format = """
$time\
$status\
$cmd_duration\
"""

palette = 'wallust'

[palettes.wallust]

bg = '#0D1207'
fg = '#B6AEA6'
color0 = '#2D3130'
color1 = '#5D4C3A'
color2 = '#5D6A4B'
color3 = '#9A7B41'
color4 = '#6C8185'
color5 = '#6F8A4F'
color6 = '#97B0AA'
color7 = '#8E8377'
color8 = '#635C53'
color9 = '#5D4C3A'
color10 = '#5D6A4B'
color11 = '#9A7B41'
color12 = '#6C8185'
color13 = '#6F8A4F'
color14 = '#97B0AA'
color15 = '#8E8377'

[os]
format = '[$symbol]($style)'
style = '#97B0AA'
disabled = false

[os.symbols]
Arch = "󰣇 "

[username]
style_user = '#B6AEA6'
style_root = '#6F8A4F'
format = '[$user]($style) '
show_always = true

[directory]
truncation_length = 4
truncate_to_repo  = true
format            ='[$path]($style)[$read_only]($read_only_style) '
style = "#9A7B41"
read_only = "󰌾 "
read_only_style = "red"
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "
style = "#6F8A4F"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#6C8185"

[character]
success_symbol = "[❯](#97B0AA)"
error_symbol = "[❯](#6F8A4F)"
vimcmd_symbol = "[❮](#97B0AA)"
vimcmd_replace_one_symbol = "[❮](#9A7B41)"
vimcmd_replace_symbol = "[❮](#9A7B41)"
vimcmd_visual_symbol = "[❮](#8E8377)"

[cmd_duration]
min_time = 500
format = 'took [$duration]($style) '
style = "#8E8377"

[status]
format = '[$symbol$status]($style) '
style = "#6F8A4F"
symbol = "✗ "
not_executable_symbol = " "
not_found_symbol = " "
sigint_symbol = "󱊈 "
signal_symbol = " "
map_symbol = true

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
format = '[$symbol$percentage]($style) '

[time]
format = '[  $time ]($style)'
disabled = false
time_format = "%R" # Hour:Minute Format
style = "#8E8377"