#   _________ __                      .__    .__        
#  /   _____//  |______ _______  _____|  |__ |__|_____  
#  \_____  \\   __\__  \\_  __ \/  ___/  |  \|  \____ \ 
#  /        \|  |  / __ \|  | \/\___ \|   Y  \  |  |_> >
# /_______  /|__| (____  /__|  /____  >___|  /__|   __/ 
#         \/           \/           \/     \/   |__|    

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$character\
"""
right_format = """
$time\
$status\
$cmd_duration\
"""

palette = 'wallust'

[palettes.wallust]

bg = '#192128'
fg = '#B2ACB4'
color0 = '#413738'
color1 = '#564859'
color2 = '#526068'
color3 = '#975D56'
color4 = '#907C8B'
color5 = '#758A9C'
color6 = '#D3716E'
color7 = '#89808C'
color8 = '#605A62'
color9 = '#564859'
color10 = '#526068'
color11 = '#975D56'
color12 = '#907C8B'
color13 = '#758A9C'
color14 = '#D3716E'
color15 = '#89808C'

[os]
format = '[$symbol]($style)'
style = '#D3716E'
disabled = false

[os.symbols]
Arch = "󰣇 "

[username]
style_user = '#B2ACB4'
style_root = '#758A9C'
format = '[$user]($style) '
show_always = true

[directory]
truncation_length = 4
truncate_to_repo  = true
format            ='[$path]($style)[$read_only]($read_only_style) '
style = "#975D56"
read_only = "󰌾 "
read_only_style = "red"
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "
style = "#758A9C"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#907C8B"

[character]
success_symbol = "[❯](#D3716E)"
error_symbol = "[❯](#758A9C)"
vimcmd_symbol = "[❮](#D3716E)"
vimcmd_replace_one_symbol = "[❮](#975D56)"
vimcmd_replace_symbol = "[❮](#975D56)"
vimcmd_visual_symbol = "[❮](#89808C)"

[cmd_duration]
min_time = 500
format = 'took [$duration]($style) '
style = "#89808C"

[status]
format = '[$symbol$status]($style) '
style = "#758A9C"
symbol = "✗ "
not_executable_symbol = " "
not_found_symbol = " "
sigint_symbol = "󱊈 "
signal_symbol = " "
map_symbol = true

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
format = '[$symbol$percentage]($style) '

[time]
format = '[  $time ]($style)'
disabled = false
time_format = "%R" # Hour:Minute Format
style = "#89808C"