#   _________ __                      .__    .__        
#  /   _____//  |______ _______  _____|  |__ |__|_____  
#  \_____  \\   __\__  \\_  __ \/  ___/  |  \|  \____ \ 
#  /        \|  |  / __ \|  | \/\___ \|   Y  \  |  |_> >
# /_______  /|__| (____  /__|  /____  >___|  /__|   __/ 
#         \/           \/           \/     \/   |__|    

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$character\
"""
right_format = """
$time\
$status\
$cmd_duration\
"""

palette = 'wallust'

[palettes.wallust]

bg = '#231B1D'
fg = '#B1AAAA'
color0 = '#201E19'
color1 = '#524242'
color2 = '#516771'
color3 = '#967F84'
color4 = '#599181'
color5 = '#E45D4B'
color6 = '#9E9375'
color7 = '#867D7D'
color8 = '#5E5757'
color9 = '#524242'
color10 = '#516771'
color11 = '#967F84'
color12 = '#599181'
color13 = '#E45D4B'
color14 = '#9E9375'
color15 = '#867D7D'

[os]
format = '[$symbol]($style)'
style = '#9E9375'
disabled = false

[os.symbols]
Arch = "󰣇 "

[username]
style_user = '#B1AAAA'
style_root = '#E45D4B'
format = '[$user]($style) '
show_always = true

[directory]
truncation_length = 4
truncate_to_repo  = true
format            ='[$path]($style)[$read_only]($read_only_style) '
style = "#967F84"
read_only = "󰌾 "
read_only_style = "red"
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "
style = "#E45D4B"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#599181"

[character]
success_symbol = "[❯](#9E9375)"
error_symbol = "[❯](#E45D4B)"
vimcmd_symbol = "[❮](#9E9375)"
vimcmd_replace_one_symbol = "[❮](#967F84)"
vimcmd_replace_symbol = "[❮](#967F84)"
vimcmd_visual_symbol = "[❮](#867D7D)"

[cmd_duration]
min_time = 500
format = 'took [$duration]($style) '
style = "#867D7D"

[status]
format = '[$symbol$status]($style) '
style = "#E45D4B"
symbol = "✗ "
not_executable_symbol = " "
not_found_symbol = " "
sigint_symbol = "󱊈 "
signal_symbol = " "
map_symbol = true

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
format = '[$symbol$percentage]($style) '

[time]
format = '[  $time ]($style)'
disabled = false
time_format = "%R" # Hour:Minute Format
style = "#867D7D"