-- Auto-generated by Wallust. DO NOT EDIT.
return {
  bg       = "{{background}}",
  fg       = "{{foreground}}",

  black    = "{{color0}}",
  red      = "{{color1}}",
  green    = "{{color2}}",
  yellow   = "{{color3}}",
  blue     = "{{color4}}",
  magenta  = "{{color5}}",
  cyan     = "{{color6}}",
  white    = "{{color7}}",

  brblack  = "{{color8}}",
  brred    = "{{color9}}",
  brgreen  = "{{color10}}",
  bryellow = "{{color11}}",
  brblue   = "{{color12}}",
  brmagenta= "{{color13}}",
  brcyan   = "{{color14}}",
  brwhite  = "{{color15}}",
}
